baseurl = "https://jensrantil.github.io"
languageCode = "en"
title = "JensRantil"
theme = "hugo-coder"
disqusShortname = "jensrantil"
googleAnalytics = "UA-40929103-1"
paginate = 20
defaultContentLanguage = "en"

[params]
author = "Jens Rantil"
description = 'Backend/security/infrastructure/DevOps engineer, engineering mathematics, traveller, nerd, juggler, guitar/african drum player. Inspired Swede.'
avatarURL = "images/avatar.jpg"
keywords = "blog,developer,personal"
commit = "https://github.com/luizdepra/hugo-coder/tree/"
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[taxonomies]
tag = "tags"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "post/"

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "/page/about-me/"

[[params.social]]
name = "E-mail"
icon = "fa fa-2x fa-envelope"
weight = 0
url = "mailto:jens.rantil@gmail.com"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/JensRantil/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/JensRantil/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/jensrantil/"

[[params.social]]
name = "Stack Overflow"
icon = "fa fa-2x fa-stack-overflow"
weight = 4
url = "https://www.stackoverflow.com/Ztyx/"

[[params.social]]
name = "Quora"
icon = "fa fa-2x fa-quora"
weight = 5
url = "https://www.quora.com/profile/Jens-Rantil"

[[params.social]]
name = "Meetup"
icon = "fa fa-2x fa-meetup"
weight = 6
url = "https://www.meetup.com/members/13195237/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 7
url = "https://jensrantil.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"
