name: ShellCheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ShellCheck
      uses: ludeeus/action-shellcheck@v1

    - name: Run ShellCheck
      run: shellcheck pre-commit.sh
